### ISSUE TITLE
speedtest.py not a accurate read out

### ISSUE THREAD

**Issue by markC85** [shotgunsoftware/shotgun-toolbox#5]
Hey guys I don't think your speedtest.py is giving a accurate picture since its in direct conflict with the speedtest.net site results when you run a speed test. I am getting a ping ms 0 / download Mbps 102.11 / Upload Mbps 0.73 and the tool says I am getting 28.73 Mbit/s down and 2.80 Mbits Up.

This is the result:
Retrieving speedtest.net configuration...
Testing from Bel Air Internet, LLC (162.208.95.134)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Sprint (Anaheim, CA) [16.72 km]: 11.851 ms
Testing download speed................................................................................
Download: 28.72 Mbit/s
Testing upload speed....................................................................................................
Upload: 2.80 Mbit/s

So either the code is pulling from a server farther away then the main site is or the speedtest.net sight is lying on there results and in turn I wonder if its safe to even pull data from the site.

**Comment by rlyne** [comment]
Hi there!

Apologies for the late reply and thank you for submitting this issue.

We use speedtest-cli which whilst not as accurate as dedicated bandwidth testing tools allows us to get a feel for client's bandwidth and help diagnose issues related to Shotgun connectivity. There are a number of reasons you might see inconsistent results from those on speedtest.net, including:
- Other devices on your network utilising bandwidth whilst a speedtest is being performed
- Intermittent connectivity issues, especially if the test is performed from a WLAN client, for example
- speedtest.net uses socket connections, whereas speedtest-cli uses HTTP
- As speedtest-cli is written in Python, its performance can vary depending upon hardware capacity and Python interpreter version which can often mean it reports differently to the web-based speedtest.net

We download the latest speedtest-cli on demand when our connectivity tool is run, although if for any reason it can't be downloaded then an included cached version is used instead. We've updated this cached version in case this is what you were using. Please give it a go and let us know how you get on.

Kind regards,

Reece
